# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OverWriteTestDlg.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OverWriteTest(object):
    def setupUi(self, OverWriteTest):
        OverWriteTest.setObjectName("OverWriteTest")
        OverWriteTest.setWindowModality(QtCore.Qt.ApplicationModal)
        OverWriteTest.resize(539, 196)
        OverWriteTest.setWhatsThis("")
        OverWriteTest.setModal(True)
        self.buttonBox = QtWidgets.QDialogButtonBox(OverWriteTest)
        self.buttonBox.setGeometry(QtCore.QRect(30, 140, 481, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.No|QtWidgets.QDialogButtonBox.NoToAll|QtWidgets.QDialogButtonBox.Yes|QtWidgets.QDialogButtonBox.YesToAll)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(OverWriteTest)
        self.label.setGeometry(QtCore.QRect(70, 30, 451, 81))
        self.label.setWordWrap(True)
        self.label.setObjectName("label")

        self.retranslateUi(OverWriteTest)
        self.buttonBox.accepted.connect(OverWriteTest.accept)
        self.buttonBox.rejected.connect(OverWriteTest.reject)
        QtCore.QMetaObject.connectSlotsByName(OverWriteTest)

    def retranslateUi(self, OverWriteTest):
        _translate = QtCore.QCoreApplication.translate
        OverWriteTest.setWindowTitle(_translate("OverWriteTest", "Test Exists"))
        self.label.setText(_translate("OverWriteTest", "There is a test that already exists in the testbed that matches the lexical unit XX. Do you want to overwrite it?"))
