# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LiveRuleTester.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1271, 715)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabRules = QtWidgets.QTabWidget(self.centralwidget)
        self.tabRules.setEnabled(True)
        self.tabRules.setGeometry(QtCore.QRect(20, 346, 777, 148))
        self.tabRules.setTabPosition(QtWidgets.QTabWidget.South)
        self.tabRules.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabRules.setObjectName("tabRules")
        self.tab_transfer_rules = QtWidgets.QWidget()
        self.tab_transfer_rules.setObjectName("tab_transfer_rules")
        self.listTransferRules = QtWidgets.QListView(self.tab_transfer_rules)
        self.listTransferRules.setGeometry(QtCore.QRect(0, 0, 771, 120))
        self.listTransferRules.setStyleSheet("background-color: rgb(240, 221, 255);")
        self.listTransferRules.setEditTriggers(QtWidgets.QAbstractItemView.EditKeyPressed)
        self.listTransferRules.setObjectName("listTransferRules")
        self.tabRules.addTab(self.tab_transfer_rules, "")
        self.tab_interchunk_rules = QtWidgets.QWidget()
        self.tab_interchunk_rules.setObjectName("tab_interchunk_rules")
        self.listInterChunkRules = QtWidgets.QListView(self.tab_interchunk_rules)
        self.listInterChunkRules.setEnabled(True)
        self.listInterChunkRules.setGeometry(QtCore.QRect(0, 0, 771, 120))
        self.listInterChunkRules.setStyleSheet("background-color: rgb(255, 225, 194);")
        self.listInterChunkRules.setObjectName("listInterChunkRules")
        self.tabRules.addTab(self.tab_interchunk_rules, "")
        self.tab_postchunk_rules = QtWidgets.QWidget()
        self.tab_postchunk_rules.setObjectName("tab_postchunk_rules")
        self.listPostChunkRules = QtWidgets.QListView(self.tab_postchunk_rules)
        self.listPostChunkRules.setGeometry(QtCore.QRect(0, 0, 771, 120))
        self.listPostChunkRules.setStyleSheet("background-color: rgb(222, 255, 246);")
        self.listPostChunkRules.setObjectName("listPostChunkRules")
        self.tabRules.addTab(self.tab_postchunk_rules, "")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 9, 81, 23))
        self.label.setObjectName("label")
        self.TransferFileBrowseButton = QtWidgets.QPushButton(self.centralwidget)
        self.TransferFileBrowseButton.setEnabled(False)
        self.TransferFileBrowseButton.setGeometry(QtCore.QRect(290, 5, 101, 31))
        self.TransferFileBrowseButton.setObjectName("TransferFileBrowseButton")
        self.TransferFileEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.TransferFileEdit.setGeometry(QtCore.QRect(110, 5, 171, 29))
        self.TransferFileEdit.setText("")
        self.TransferFileEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.TransferFileEdit.setObjectName("TransferFileEdit")
        self.BilingFileEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.BilingFileEdit.setGeometry(QtCore.QRect(550, 5, 171, 29))
        self.BilingFileEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.BilingFileEdit.setObjectName("BilingFileEdit")
        self.BilingFileBrowseButton = QtWidgets.QPushButton(self.centralwidget)
        self.BilingFileBrowseButton.setEnabled(False)
        self.BilingFileBrowseButton.setGeometry(QtCore.QRect(728, 5, 101, 31))
        self.BilingFileBrowseButton.setObjectName("BilingFileBrowseButton")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(410, 9, 131, 23))
        self.label_2.setObjectName("label_2")
        self.tabSource = QtWidgets.QTabWidget(self.centralwidget)
        self.tabSource.setGeometry(QtCore.QRect(20, 75, 1231, 225))
        self.tabSource.setTabPosition(QtWidgets.QTabWidget.South)
        self.tabSource.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabSource.setMovable(False)
        self.tabSource.setObjectName("tabSource")
        self.tab_select_words = QtWidgets.QWidget()
        self.tab_select_words.setObjectName("tab_select_words")
        self.SentCombo = QtWidgets.QComboBox(self.tab_select_words)
        self.SentCombo.setGeometry(QtCore.QRect(0, 0, 1225, 29))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.SentCombo.setFont(font)
        self.SentCombo.setMaxVisibleItems(30)
        self.SentCombo.setObjectName("SentCombo")
        self.scrollArea = QtWidgets.QScrollArea(self.tab_select_words)
        self.scrollArea.setGeometry(QtCore.QRect(0, 30, 1225, 103))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.scrollArea.setFont(font)
        self.scrollArea.setStyleSheet("background-color: rgb(255, 220, 213);")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1223, 101))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.SelectedWordsEdit = QtWidgets.QTextEdit(self.tab_select_words)
        self.SelectedWordsEdit.setGeometry(QtCore.QRect(0, 135, 1225, 61))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.SelectedWordsEdit.setFont(font)
        self.SelectedWordsEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.SelectedWordsEdit.setStyleSheet("background-color: rgb(225, 255, 255);")
        self.SelectedWordsEdit.setReadOnly(True)
        self.SelectedWordsEdit.setObjectName("SelectedWordsEdit")
        self.tabSource.addTab(self.tab_select_words, "")
        self.tab_select_sentences = QtWidgets.QWidget()
        self.tab_select_sentences.setObjectName("tab_select_sentences")
        self.listSentences = QtWidgets.QListView(self.tab_select_sentences)
        self.listSentences.setGeometry(QtCore.QRect(0, 0, 1225, 132))
        self.listSentences.setStyleSheet("background-color: rgb(255, 220, 213);")
        self.listSentences.setObjectName("listSentences")
        self.SelectedSentencesEdit = QtWidgets.QTextEdit(self.tab_select_sentences)
        self.SelectedSentencesEdit.setGeometry(QtCore.QRect(0, 135, 1225, 61))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.SelectedSentencesEdit.setFont(font)
        self.SelectedSentencesEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.SelectedSentencesEdit.setStyleSheet("background-color: rgb(225, 255, 255);")
        self.SelectedSentencesEdit.setReadOnly(True)
        self.SelectedSentencesEdit.setObjectName("SelectedSentencesEdit")
        self.tabSource.addTab(self.tab_select_sentences, "")
        self.tab_manual_entry = QtWidgets.QWidget()
        self.tab_manual_entry.setObjectName("tab_manual_entry")
        self.ManualEdit = QtWidgets.QPlainTextEdit(self.tab_manual_entry)
        self.ManualEdit.setGeometry(QtCore.QRect(0, 0, 1225, 196))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.ManualEdit.setFont(font)
        self.ManualEdit.setStyleSheet("background-color: rgb(225, 255, 255);")
        self.ManualEdit.setObjectName("ManualEdit")
        self.tabSource.addTab(self.tab_manual_entry, "")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 509, 111, 23))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 45, 111, 23))
        self.label_4.setObjectName("label_4")
        self.LogEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.LogEdit.setGeometry(QtCore.QRect(800, 346, 451, 122))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.LogEdit.setFont(font)
        self.LogEdit.setStyleSheet("background-color: rgb(251, 255, 206);")
        self.LogEdit.setReadOnly(True)
        self.LogEdit.setObjectName("LogEdit")
        self.TestButton = QtWidgets.QPushButton(self.centralwidget)
        self.TestButton.setGeometry(QtCore.QRect(490, 502, 101, 31))
        self.TestButton.setObjectName("TestButton")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 314, 211, 23))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(800, 316, 141, 23))
        self.label_6.setObjectName("label_6")
        self.SourceTextName = QtWidgets.QLabel(self.centralwidget)
        self.SourceTextName.setGeometry(QtCore.QRect(848, 9, 91, 23))
        self.SourceTextName.setObjectName("SourceTextName")
        self.SourceFileEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.SourceFileEdit.setGeometry(QtCore.QRect(950, 5, 171, 29))
        self.SourceFileEdit.setText("")
        self.SourceFileEdit.setObjectName("SourceFileEdit")
        self.refreshButton = QtWidgets.QPushButton(self.centralwidget)
        self.refreshButton.setGeometry(QtCore.QRect(630, 310, 161, 31))
        self.refreshButton.setObjectName("refreshButton")
        self.selectAllButton = QtWidgets.QPushButton(self.centralwidget)
        self.selectAllButton.setGeometry(QtCore.QRect(240, 310, 101, 31))
        self.selectAllButton.setObjectName("selectAllButton")
        self.upButton = QtWidgets.QPushButton(self.centralwidget)
        self.upButton.setGeometry(QtCore.QRect(490, 310, 41, 31))
        self.upButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("UpArrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.upButton.setIcon(icon)
        self.upButton.setObjectName("upButton")
        self.downButton = QtWidgets.QPushButton(self.centralwidget)
        self.downButton.setGeometry(QtCore.QRect(540, 310, 41, 31))
        self.downButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("DownArrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.downButton.setIcon(icon1)
        self.downButton.setObjectName("downButton")
        self.ChooseSourceButton = QtWidgets.QPushButton(self.centralwidget)
        self.ChooseSourceButton.setEnabled(False)
        self.ChooseSourceButton.setGeometry(QtCore.QRect(1130, 5, 101, 31))
        self.ChooseSourceButton.setObjectName("ChooseSourceButton")
        self.unselectAllButton = QtWidgets.QPushButton(self.centralwidget)
        self.unselectAllButton.setGeometry(QtCore.QRect(360, 310, 101, 31))
        self.unselectAllButton.setObjectName("unselectAllButton")
        self.TargetTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.TargetTextEdit.setGeometry(QtCore.QRect(20, 539, 1231, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.TargetTextEdit.setFont(font)
        self.TargetTextEdit.setStyleSheet("background-color: rgb(229, 255, 236);")
        self.TargetTextEdit.setReadOnly(True)
        self.TargetTextEdit.setObjectName("TargetTextEdit")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(20, 594, 161, 23))
        self.label_7.setObjectName("label_7")
        self.SynthTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.SynthTextEdit.setGeometry(QtCore.QRect(20, 626, 1231, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.SynthTextEdit.setFont(font)
        self.SynthTextEdit.setStyleSheet("background-color: rgb(254, 194,194);")
        self.SynthTextEdit.setReadOnly(True)
        self.SynthTextEdit.setObjectName("SynthTextEdit")
        self.synthesizeButton = QtWidgets.QPushButton(self.centralwidget)
        self.synthesizeButton.setGeometry(QtCore.QRect(490, 589, 101, 31))
        self.synthesizeButton.setObjectName("synthesizeButton")
        self.refreshLexButton = QtWidgets.QPushButton(self.centralwidget)
        self.refreshLexButton.setGeometry(QtCore.QRect(630, 589, 161, 31))
        self.refreshLexButton.setObjectName("refreshLexButton")
        self.addToTestbedButton = QtWidgets.QPushButton(self.centralwidget)
        self.addToTestbedButton.setGeometry(QtCore.QRect(160, 677, 161, 31))
        self.addToTestbedButton.setObjectName("addToTestbedButton")
        self.addMultipleCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.addMultipleCheckBox.setGeometry(QtCore.QRect(340, 680, 391, 25))
        self.addMultipleCheckBox.setObjectName("addMultipleCheckBox")
        self.editTestbedButton = QtWidgets.QPushButton(self.centralwidget)
        self.editTestbedButton.setEnabled(True)
        self.editTestbedButton.setGeometry(QtCore.QRect(754, 677, 161, 31))
        self.editTestbedButton.setObjectName("editTestbedButton")
        self.viewTestbedLogButton = QtWidgets.QPushButton(self.centralwidget)
        self.viewTestbedLogButton.setEnabled(False)
        self.viewTestbedLogButton.setGeometry(QtCore.QRect(940, 677, 161, 31))
        self.viewTestbedLogButton.setObjectName("viewTestbedLogButton")
        self.TestsAddedLabel = QtWidgets.QLabel(self.centralwidget)
        self.TestsAddedLabel.setEnabled(True)
        self.TestsAddedLabel.setGeometry(QtCore.QRect(20, 680, 131, 20))
        self.TestsAddedLabel.setObjectName("TestsAddedLabel")
        self.rebuildBilingLexButton = QtWidgets.QPushButton(self.centralwidget)
        self.rebuildBilingLexButton.setGeometry(QtCore.QRect(554, 43, 161, 31))
        self.rebuildBilingLexButton.setObjectName("rebuildBilingLexButton")
        self.editTransferRulesButton = QtWidgets.QPushButton(self.centralwidget)
        self.editTransferRulesButton.setGeometry(QtCore.QRect(1090, 310, 161, 31))
        self.editTransferRulesButton.setObjectName("editTransferRulesButton")
        self.viewBilingualLexiconButton = QtWidgets.QPushButton(self.centralwidget)
        self.viewBilingualLexiconButton.setGeometry(QtCore.QRect(880, 43, 161, 31))
        self.viewBilingualLexiconButton.setObjectName("viewBilingualLexiconButton")
        self.editReplacementButton = QtWidgets.QPushButton(self.centralwidget)
        self.editReplacementButton.setGeometry(QtCore.QRect(1090, 43, 161, 31))
        self.editReplacementButton.setObjectName("editReplacementButton")
        self.selectWordsHintLabel = QtWidgets.QLabel(self.centralwidget)
        self.selectWordsHintLabel.setGeometry(QtCore.QRect(320, 278, 501, 23))
        self.selectWordsHintLabel.setObjectName("selectWordsHintLabel")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabRules.setCurrentIndex(0)
        self.tabSource.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FLExTrans Live Rule Tester"))
        self.tabRules.setTabText(self.tabRules.indexOf(self.tab_transfer_rules), _translate("MainWindow", "Transfer"))
        self.tabRules.setTabText(self.tabRules.indexOf(self.tab_interchunk_rules), _translate("MainWindow", "Interchunk"))
        self.tabRules.setTabText(self.tabRules.indexOf(self.tab_postchunk_rules), _translate("MainWindow", "Postchunk"))
        self.label.setText(_translate("MainWindow", "Rules File"))
        self.TransferFileBrowseButton.setText(_translate("MainWindow", "Browse..."))
        self.BilingFileBrowseButton.setText(_translate("MainWindow", "Browse..."))
        self.label_2.setText(_translate("MainWindow", "Biling. Dict. File"))
        self.tabSource.setTabText(self.tabSource.indexOf(self.tab_select_words), _translate("MainWindow", "Select Words"))
        self.tabSource.setTabText(self.tabSource.indexOf(self.tab_select_sentences), _translate("MainWindow", "Select Sentences"))
        self.tabSource.setTabText(self.tabSource.indexOf(self.tab_manual_entry), _translate("MainWindow", "Manual Entry"))
        self.label_3.setText(_translate("MainWindow", "Target Text"))
        self.label_4.setText(_translate("MainWindow", "Source Text"))
        self.TestButton.setText(_translate("MainWindow", "Transfer"))
        self.label_5.setText(_translate("MainWindow", "Select transfer rules to test"))
        self.label_6.setText(_translate("MainWindow", "Information"))
        self.SourceTextName.setText(_translate("MainWindow", "Text Name"))
        self.refreshButton.setText(_translate("MainWindow", "&Refresh Rules"))
        self.selectAllButton.setText(_translate("MainWindow", "&Select All"))
        self.ChooseSourceButton.setText(_translate("MainWindow", "Choose..."))
        self.unselectAllButton.setText(_translate("MainWindow", "&Unselect All"))
        self.label_7.setText(_translate("MainWindow", "Synthesized Text"))
        self.synthesizeButton.setText(_translate("MainWindow", "&Synthesize"))
        self.refreshLexButton.setText(_translate("MainWindow", "Refresh &Target Lexicon"))
        self.addToTestbedButton.setText(_translate("MainWindow", "&Add to Testbed"))
        self.addMultipleCheckBox.setText(_translate("MainWindow", "Add multiple words to the testbed word by word"))
        self.editTestbedButton.setText(_translate("MainWindow", "&Edit Testbed"))
        self.viewTestbedLogButton.setText(_translate("MainWindow", "&View Testbed Log"))
        self.TestsAddedLabel.setText(_translate("MainWindow", "X tests added."))
        self.rebuildBilingLexButton.setText(_translate("MainWindow", "Rebuild &Bilingual Lexicon"))
        self.editTransferRulesButton.setText(_translate("MainWindow", "E&dit Transfer Rules"))
        self.viewBilingualLexiconButton.setText(_translate("MainWindow", "&View Bilingual Lexicon"))
        self.editReplacementButton.setText(_translate("MainWindow", "Edit Replacement &File"))
        self.selectWordsHintLabel.setText(_translate("MainWindow", "Hover over a word to see its bilingual dictionary entry."))
