# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LiveRuleTester.ui'
#
# Created: Wed May 23 13:17:44 2018
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1271, 817)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabRules = QtGui.QTabWidget(self.centralwidget)
        self.tabRules.setEnabled(True)
        self.tabRules.setGeometry(QtCore.QRect(20, 384, 777, 148))
        self.tabRules.setTabPosition(QtGui.QTabWidget.South)
        self.tabRules.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabRules.setObjectName(_fromUtf8("tabRules"))
        self.tab_transfer_rules = QtGui.QWidget()
        self.tab_transfer_rules.setObjectName(_fromUtf8("tab_transfer_rules"))
        self.listTransferRules = QtGui.QListView(self.tab_transfer_rules)
        self.listTransferRules.setGeometry(QtCore.QRect(0, 0, 771, 120))
        self.listTransferRules.setStyleSheet(_fromUtf8("background-color: rgb(240, 221, 255);"))
        self.listTransferRules.setEditTriggers(QtGui.QAbstractItemView.EditKeyPressed)
        self.listTransferRules.setObjectName(_fromUtf8("listTransferRules"))
        self.tabRules.addTab(self.tab_transfer_rules, _fromUtf8(""))
        self.tab_interchunk_rules = QtGui.QWidget()
        self.tab_interchunk_rules.setObjectName(_fromUtf8("tab_interchunk_rules"))
        self.listInterChunkRules = QtGui.QListView(self.tab_interchunk_rules)
        self.listInterChunkRules.setEnabled(True)
        self.listInterChunkRules.setGeometry(QtCore.QRect(0, 0, 771, 120))
        self.listInterChunkRules.setStyleSheet(_fromUtf8("background-color: rgb(255, 225, 194);"))
        self.listInterChunkRules.setObjectName(_fromUtf8("listInterChunkRules"))
        self.tabRules.addTab(self.tab_interchunk_rules, _fromUtf8(""))
        self.tab_postchunk_rules = QtGui.QWidget()
        self.tab_postchunk_rules.setObjectName(_fromUtf8("tab_postchunk_rules"))
        self.listPostChunkRules = QtGui.QListView(self.tab_postchunk_rules)
        self.listPostChunkRules.setGeometry(QtCore.QRect(0, 0, 771, 120))
        self.listPostChunkRules.setStyleSheet(_fromUtf8("background-color: rgb(222, 255, 246);"))
        self.listPostChunkRules.setObjectName(_fromUtf8("listPostChunkRules"))
        self.tabRules.addTab(self.tab_postchunk_rules, _fromUtf8(""))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 23, 81, 23))
        self.label.setObjectName(_fromUtf8("label"))
        self.TransferFileBrowseButton = QtGui.QPushButton(self.centralwidget)
        self.TransferFileBrowseButton.setGeometry(QtCore.QRect(290, 19, 101, 31))
        self.TransferFileBrowseButton.setObjectName(_fromUtf8("TransferFileBrowseButton"))
        self.TransferFileEdit = QtGui.QLineEdit(self.centralwidget)
        self.TransferFileEdit.setGeometry(QtCore.QRect(110, 19, 171, 29))
        self.TransferFileEdit.setText(_fromUtf8(""))
        self.TransferFileEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.TransferFileEdit.setObjectName(_fromUtf8("TransferFileEdit"))
        self.BilingFileEdit = QtGui.QLineEdit(self.centralwidget)
        self.BilingFileEdit.setGeometry(QtCore.QRect(550, 19, 171, 29))
        self.BilingFileEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.BilingFileEdit.setObjectName(_fromUtf8("BilingFileEdit"))
        self.BilingFileBrowseButton = QtGui.QPushButton(self.centralwidget)
        self.BilingFileBrowseButton.setGeometry(QtCore.QRect(728, 19, 101, 31))
        self.BilingFileBrowseButton.setObjectName(_fromUtf8("BilingFileBrowseButton"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(410, 23, 131, 23))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.tabSource = QtGui.QTabWidget(self.centralwidget)
        self.tabSource.setGeometry(QtCore.QRect(20, 100, 1231, 225))
        self.tabSource.setTabPosition(QtGui.QTabWidget.South)
        self.tabSource.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabSource.setMovable(False)
        self.tabSource.setObjectName(_fromUtf8("tabSource"))
        self.tab_select_words = QtGui.QWidget()
        self.tab_select_words.setObjectName(_fromUtf8("tab_select_words"))
        self.SentCombo = QtGui.QComboBox(self.tab_select_words)
        self.SentCombo.setGeometry(QtCore.QRect(0, 0, 1225, 29))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.SentCombo.setFont(font)
        self.SentCombo.setObjectName(_fromUtf8("SentCombo"))
        self.scrollArea = QtGui.QScrollArea(self.tab_select_words)
        self.scrollArea.setGeometry(QtCore.QRect(0, 30, 1225, 103))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.scrollArea.setFont(font)
        self.scrollArea.setStyleSheet(_fromUtf8("background-color: rgb(255, 220, 213);"))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1223, 101))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.SelectedWordsEdit = QtGui.QTextEdit(self.tab_select_words)
        self.SelectedWordsEdit.setGeometry(QtCore.QRect(0, 135, 1225, 61))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.SelectedWordsEdit.setFont(font)
        self.SelectedWordsEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.SelectedWordsEdit.setStyleSheet(_fromUtf8("background-color: rgb(225, 255, 255);"))
        self.SelectedWordsEdit.setReadOnly(True)
        self.SelectedWordsEdit.setObjectName(_fromUtf8("SelectedWordsEdit"))
        self.tabSource.addTab(self.tab_select_words, _fromUtf8(""))
        self.tab_select_sentences = QtGui.QWidget()
        self.tab_select_sentences.setObjectName(_fromUtf8("tab_select_sentences"))
        self.listSentences = QtGui.QListView(self.tab_select_sentences)
        self.listSentences.setGeometry(QtCore.QRect(0, 0, 1225, 132))
        self.listSentences.setStyleSheet(_fromUtf8("background-color: rgb(255, 220, 213);"))
        self.listSentences.setObjectName(_fromUtf8("listSentences"))
        self.SelectedSentencesEdit = QtGui.QTextEdit(self.tab_select_sentences)
        self.SelectedSentencesEdit.setGeometry(QtCore.QRect(0, 135, 1225, 61))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.SelectedSentencesEdit.setFont(font)
        self.SelectedSentencesEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.SelectedSentencesEdit.setStyleSheet(_fromUtf8("background-color: rgb(225, 255, 255);"))
        self.SelectedSentencesEdit.setReadOnly(True)
        self.SelectedSentencesEdit.setObjectName(_fromUtf8("SelectedSentencesEdit"))
        self.tabSource.addTab(self.tab_select_sentences, _fromUtf8(""))
        self.tab_manual_entry = QtGui.QWidget()
        self.tab_manual_entry.setObjectName(_fromUtf8("tab_manual_entry"))
        self.ManualEdit = QtGui.QPlainTextEdit(self.tab_manual_entry)
        self.ManualEdit.setGeometry(QtCore.QRect(0, 0, 1225, 196))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.ManualEdit.setFont(font)
        self.ManualEdit.setStyleSheet(_fromUtf8("background-color: rgb(225, 255, 255);"))
        self.ManualEdit.setObjectName(_fromUtf8("ManualEdit"))
        self.tabSource.addTab(self.tab_manual_entry, _fromUtf8(""))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 560, 111, 23))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 70, 111, 23))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.LogEdit = QtGui.QPlainTextEdit(self.centralwidget)
        self.LogEdit.setGeometry(QtCore.QRect(800, 384, 451, 122))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.LogEdit.setFont(font)
        self.LogEdit.setStyleSheet(_fromUtf8("background-color: rgb(251, 255, 206);"))
        self.LogEdit.setReadOnly(True)
        self.LogEdit.setObjectName(_fromUtf8("LogEdit"))
        self.TestButton = QtGui.QPushButton(self.centralwidget)
        self.TestButton.setGeometry(QtCore.QRect(490, 553, 101, 31))
        self.TestButton.setObjectName(_fromUtf8("TestButton"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 352, 171, 23))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(800, 354, 141, 23))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.SourceTextName = QtGui.QLabel(self.centralwidget)
        self.SourceTextName.setGeometry(QtCore.QRect(848, 23, 91, 23))
        self.SourceTextName.setObjectName(_fromUtf8("SourceTextName"))
        self.SourceFileEdit = QtGui.QLineEdit(self.centralwidget)
        self.SourceFileEdit.setGeometry(QtCore.QRect(950, 19, 171, 29))
        self.SourceFileEdit.setText(_fromUtf8(""))
        self.SourceFileEdit.setObjectName(_fromUtf8("SourceFileEdit"))
        self.refreshButton = QtGui.QPushButton(self.centralwidget)
        self.refreshButton.setGeometry(QtCore.QRect(630, 348, 161, 31))
        self.refreshButton.setObjectName(_fromUtf8("refreshButton"))
        self.selectAllButton = QtGui.QPushButton(self.centralwidget)
        self.selectAllButton.setGeometry(QtCore.QRect(200, 348, 101, 31))
        self.selectAllButton.setObjectName(_fromUtf8("selectAllButton"))
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(20, 657, 1231, 10))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(20, 334, 1231, 16))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.line_3 = QtGui.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(20, 55, 1231, 16))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.upButton = QtGui.QPushButton(self.centralwidget)
        self.upButton.setGeometry(QtCore.QRect(450, 348, 41, 31))
        self.upButton.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("UpArrow.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.upButton.setIcon(icon)
        self.upButton.setObjectName(_fromUtf8("upButton"))
        self.downButton = QtGui.QPushButton(self.centralwidget)
        self.downButton.setGeometry(QtCore.QRect(500, 348, 41, 31))
        self.downButton.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("DownArrow.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.downButton.setIcon(icon1)
        self.downButton.setObjectName(_fromUtf8("downButton"))
        self.ChooseSourceButton = QtGui.QPushButton(self.centralwidget)
        self.ChooseSourceButton.setEnabled(False)
        self.ChooseSourceButton.setGeometry(QtCore.QRect(1130, 19, 101, 31))
        self.ChooseSourceButton.setObjectName(_fromUtf8("ChooseSourceButton"))
        self.unselectAllButton = QtGui.QPushButton(self.centralwidget)
        self.unselectAllButton.setGeometry(QtCore.QRect(320, 348, 101, 31))
        self.unselectAllButton.setObjectName(_fromUtf8("unselectAllButton"))
        self.TargetTextEdit = QtGui.QTextEdit(self.centralwidget)
        self.TargetTextEdit.setGeometry(QtCore.QRect(20, 590, 1231, 61))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.TargetTextEdit.setFont(font)
        self.TargetTextEdit.setStyleSheet(_fromUtf8("background-color: rgb(229, 255, 236);"))
        self.TargetTextEdit.setReadOnly(True)
        self.TargetTextEdit.setObjectName(_fromUtf8("TargetTextEdit"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(20, 675, 161, 23))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.SynthTextEdit = QtGui.QTextEdit(self.centralwidget)
        self.SynthTextEdit.setGeometry(QtCore.QRect(20, 707, 1231, 61))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.SynthTextEdit.setFont(font)
        self.SynthTextEdit.setStyleSheet(_fromUtf8("background-color: rgb(254, 194,194);"))
        self.SynthTextEdit.setReadOnly(True)
        self.SynthTextEdit.setObjectName(_fromUtf8("SynthTextEdit"))
        self.line_4 = QtGui.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(20, 540, 1231, 10))
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.synthesizeButton = QtGui.QPushButton(self.centralwidget)
        self.synthesizeButton.setGeometry(QtCore.QRect(490, 670, 101, 31))
        self.synthesizeButton.setObjectName(_fromUtf8("synthesizeButton"))
        self.refreshLexButton = QtGui.QPushButton(self.centralwidget)
        self.refreshLexButton.setGeometry(QtCore.QRect(630, 670, 201, 31))
        self.refreshLexButton.setObjectName(_fromUtf8("refreshLexButton"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1271, 31))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabRules.setCurrentIndex(2)
        self.tabSource.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "FLExTrans Live Rule Tester", None))
        self.tabRules.setTabText(self.tabRules.indexOf(self.tab_transfer_rules), _translate("MainWindow", "Transfer", None))
        self.tabRules.setTabText(self.tabRules.indexOf(self.tab_interchunk_rules), _translate("MainWindow", "Interchunk", None))
        self.tabRules.setTabToolTip(self.tabRules.indexOf(self.tab_interchunk_rules), _translate("MainWindow", "Not Implemented", None))
        self.tabRules.setTabText(self.tabRules.indexOf(self.tab_postchunk_rules), _translate("MainWindow", "Postchunk", None))
        self.tabRules.setTabToolTip(self.tabRules.indexOf(self.tab_postchunk_rules), _translate("MainWindow", "Not Implemented", None))
        self.label.setText(_translate("MainWindow", "Rules File", None))
        self.TransferFileBrowseButton.setText(_translate("MainWindow", "Browse...", None))
        self.BilingFileBrowseButton.setText(_translate("MainWindow", "Browse...", None))
        self.label_2.setText(_translate("MainWindow", "Biling. Dict. File", None))
        self.tabSource.setTabText(self.tabSource.indexOf(self.tab_select_words), _translate("MainWindow", "Select Words", None))
        self.tabSource.setTabText(self.tabSource.indexOf(self.tab_select_sentences), _translate("MainWindow", "Select Sentences", None))
        self.tabSource.setTabText(self.tabSource.indexOf(self.tab_manual_entry), _translate("MainWindow", "Manual Entry", None))
        self.label_3.setText(_translate("MainWindow", "Target Text", None))
        self.label_4.setText(_translate("MainWindow", "Source Text", None))
        self.TestButton.setText(_translate("MainWindow", "&Test", None))
        self.label_5.setText(_translate("MainWindow", "Select Rules to Test", None))
        self.label_6.setText(_translate("MainWindow", "Information", None))
        self.SourceTextName.setText(_translate("MainWindow", "Text Name", None))
        self.refreshButton.setText(_translate("MainWindow", "&Refresh Rules", None))
        self.selectAllButton.setText(_translate("MainWindow", "&Select All", None))
        self.ChooseSourceButton.setText(_translate("MainWindow", "Choose...", None))
        self.unselectAllButton.setText(_translate("MainWindow", "&Unselect All", None))
        self.label_7.setText(_translate("MainWindow", "Synthesized Text", None))
        self.synthesizeButton.setText(_translate("MainWindow", "&Synthesize", None))
        self.refreshLexButton.setText(_translate("MainWindow", "Refresh Target &Lexicon", None))

