# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LiveRuleTester.ui'
#
# Created: Wed Sep 28 11:19:34 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1679, 1081)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabRules = QtGui.QTabWidget(self.centralwidget)
        self.tabRules.setEnabled(True)
        self.tabRules.setGeometry(QtCore.QRect(20, 631, 781, 321))
        self.tabRules.setTabPosition(QtGui.QTabWidget.South)
        self.tabRules.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabRules.setObjectName(_fromUtf8("tabRules"))
        self.tab_transfer_rules = QtGui.QWidget()
        self.tab_transfer_rules.setObjectName(_fromUtf8("tab_transfer_rules"))
        self.listTransferRules = QtGui.QListView(self.tab_transfer_rules)
        self.listTransferRules.setGeometry(QtCore.QRect(0, 0, 775, 286))
        self.listTransferRules.setStyleSheet(_fromUtf8("background-color: rgb(240, 221, 255);"))
        self.listTransferRules.setEditTriggers(QtGui.QAbstractItemView.EditKeyPressed)
        self.listTransferRules.setObjectName(_fromUtf8("listTransferRules"))
        self.tabRules.addTab(self.tab_transfer_rules, _fromUtf8(""))
        self.tab_interchunk_rules = QtGui.QWidget()
        self.tab_interchunk_rules.setObjectName(_fromUtf8("tab_interchunk_rules"))
        self.listInterchunkRules = QtGui.QListView(self.tab_interchunk_rules)
        self.listInterchunkRules.setEnabled(True)
        self.listInterchunkRules.setGeometry(QtCore.QRect(0, 0, 775, 286))
        self.listInterchunkRules.setStyleSheet(_fromUtf8("background-color: rgb(255, 225, 194);"))
        self.listInterchunkRules.setObjectName(_fromUtf8("listInterchunkRules"))
        self.tabRules.addTab(self.tab_interchunk_rules, _fromUtf8(""))
        self.tab_postchunk_rules = QtGui.QWidget()
        self.tab_postchunk_rules.setObjectName(_fromUtf8("tab_postchunk_rules"))
        self.listPostChunkRules = QtGui.QListView(self.tab_postchunk_rules)
        self.listPostChunkRules.setGeometry(QtCore.QRect(0, 0, 775, 286))
        self.listPostChunkRules.setStyleSheet(_fromUtf8("background-color: rgb(222, 255, 246);"))
        self.listPostChunkRules.setObjectName(_fromUtf8("listPostChunkRules"))
        self.tabRules.addTab(self.tab_postchunk_rules, _fromUtf8(""))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 23, 111, 23))
        self.label.setObjectName(_fromUtf8("label"))
        self.TransferFileBrowseButton = QtGui.QPushButton(self.centralwidget)
        self.TransferFileBrowseButton.setGeometry(QtCore.QRect(370, 10, 131, 40))
        self.TransferFileBrowseButton.setObjectName(_fromUtf8("TransferFileBrowseButton"))
        self.TransferFileEdit = QtGui.QLineEdit(self.centralwidget)
        self.TransferFileEdit.setGeometry(QtCore.QRect(130, 19, 221, 29))
        self.TransferFileEdit.setText(_fromUtf8(""))
        self.TransferFileEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.TransferFileEdit.setObjectName(_fromUtf8("TransferFileEdit"))
        self.BilingFileEdit = QtGui.QLineEdit(self.centralwidget)
        self.BilingFileEdit.setGeometry(QtCore.QRect(680, 19, 221, 29))
        self.BilingFileEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.BilingFileEdit.setObjectName(_fromUtf8("BilingFileEdit"))
        self.BilingFileBrowseButton = QtGui.QPushButton(self.centralwidget)
        self.BilingFileBrowseButton.setGeometry(QtCore.QRect(920, 10, 131, 40))
        self.BilingFileBrowseButton.setObjectName(_fromUtf8("BilingFileBrowseButton"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(520, 23, 161, 23))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.tabSource = QtGui.QTabWidget(self.centralwidget)
        self.tabSource.setGeometry(QtCore.QRect(20, 110, 1631, 281))
        self.tabSource.setTabPosition(QtGui.QTabWidget.South)
        self.tabSource.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabSource.setMovable(False)
        self.tabSource.setObjectName(_fromUtf8("tabSource"))
        self.tab_select_words = QtGui.QWidget()
        self.tab_select_words.setObjectName(_fromUtf8("tab_select_words"))
        self.SelectedWordsEdit = QtGui.QPlainTextEdit(self.tab_select_words)
        self.SelectedWordsEdit.setGeometry(QtCore.QRect(0, 185, 1625, 61))
        self.SelectedWordsEdit.setStyleSheet(_fromUtf8("background-color: rgb(193, 250, 255);"))
        self.SelectedWordsEdit.setObjectName(_fromUtf8("SelectedWordsEdit"))
        self.SentCombo = QtGui.QComboBox(self.tab_select_words)
        self.SentCombo.setGeometry(QtCore.QRect(0, 0, 1625, 29))
        self.SentCombo.setObjectName(_fromUtf8("SentCombo"))
        self.scrollArea = QtGui.QScrollArea(self.tab_select_words)
        self.scrollArea.setGeometry(QtCore.QRect(0, 30, 1625, 151))
        self.scrollArea.setStyleSheet(_fromUtf8("background-color: rgb(255, 220, 213);"))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1623, 149))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.tabSource.addTab(self.tab_select_words, _fromUtf8(""))
        self.tab_select_sentences = QtGui.QWidget()
        self.tab_select_sentences.setObjectName(_fromUtf8("tab_select_sentences"))
        self.listSentences = QtGui.QListView(self.tab_select_sentences)
        self.listSentences.setGeometry(QtCore.QRect(0, 0, 1625, 181))
        self.listSentences.setStyleSheet(_fromUtf8("background-color: rgb(255, 220, 213);"))
        self.listSentences.setObjectName(_fromUtf8("listSentences"))
        self.SelectedSentencesEdit = QtGui.QPlainTextEdit(self.tab_select_sentences)
        self.SelectedSentencesEdit.setGeometry(QtCore.QRect(0, 185, 1625, 61))
        self.SelectedSentencesEdit.setStyleSheet(_fromUtf8("background-color: rgb(193, 250, 255);"))
        self.SelectedSentencesEdit.setObjectName(_fromUtf8("SelectedSentencesEdit"))
        self.tabSource.addTab(self.tab_select_sentences, _fromUtf8(""))
        self.tab_manual_entry = QtGui.QWidget()
        self.tab_manual_entry.setObjectName(_fromUtf8("tab_manual_entry"))
        self.ManualEdit = QtGui.QPlainTextEdit(self.tab_manual_entry)
        self.ManualEdit.setGeometry(QtCore.QRect(0, 0, 1625, 246))
        self.ManualEdit.setStyleSheet(_fromUtf8("background-color: rgb(193, 250, 255);"))
        self.ManualEdit.setObjectName(_fromUtf8("ManualEdit"))
        self.tabSource.addTab(self.tab_manual_entry, _fromUtf8(""))
        self.TargetTextEdit = QtGui.QPlainTextEdit(self.centralwidget)
        self.TargetTextEdit.setGeometry(QtCore.QRect(20, 440, 1631, 121))
        self.TargetTextEdit.setStyleSheet(_fromUtf8("background-color: rgb(203, 255, 211);"))
        self.TargetTextEdit.setReadOnly(True)
        self.TargetTextEdit.setObjectName(_fromUtf8("TargetTextEdit"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 410, 111, 23))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 80, 111, 23))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.LogEdit = QtGui.QPlainTextEdit(self.centralwidget)
        self.LogEdit.setGeometry(QtCore.QRect(830, 631, 821, 291))
        self.LogEdit.setStyleSheet(_fromUtf8("background-color: rgb(251, 255, 206);"))
        self.LogEdit.setReadOnly(True)
        self.LogEdit.setObjectName(_fromUtf8("LogEdit"))
        self.TestButton = QtGui.QPushButton(self.centralwidget)
        self.TestButton.setGeometry(QtCore.QRect(667, 961, 131, 40))
        self.TestButton.setObjectName(_fromUtf8("TestButton"))
        self.CloseButton = QtGui.QPushButton(self.centralwidget)
        self.CloseButton.setGeometry(QtCore.QRect(830, 961, 131, 40))
        self.CloseButton.setObjectName(_fromUtf8("CloseButton"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 601, 171, 23))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(830, 601, 141, 23))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.SourceTextName = QtGui.QLabel(self.centralwidget)
        self.SourceTextName.setGeometry(QtCore.QRect(1068, 23, 161, 23))
        self.SourceTextName.setObjectName(_fromUtf8("SourceTextName"))
        self.SourceFileEdit = QtGui.QLineEdit(self.centralwidget)
        self.SourceFileEdit.setGeometry(QtCore.QRect(1230, 19, 221, 29))
        self.SourceFileEdit.setText(_fromUtf8(""))
        self.SourceFileEdit.setObjectName(_fromUtf8("SourceFileEdit"))
        self.ChooseSourceButton = QtGui.QPushButton(self.centralwidget)
        self.ChooseSourceButton.setEnabled(False)
        self.ChooseSourceButton.setGeometry(QtCore.QRect(1470, 10, 131, 40))
        self.ChooseSourceButton.setObjectName(_fromUtf8("ChooseSourceButton"))
        self.refreshButton = QtGui.QPushButton(self.centralwidget)
        self.refreshButton.setGeometry(QtCore.QRect(667, 587, 131, 40))
        self.refreshButton.setObjectName(_fromUtf8("refreshButton"))
        self.selectAllButton = QtGui.QPushButton(self.centralwidget)
        self.selectAllButton.setGeometry(QtCore.QRect(200, 587, 131, 40))
        self.selectAllButton.setObjectName(_fromUtf8("selectAllButton"))
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(20, 571, 1631, 10))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(20, 395, 1631, 16))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.line_3 = QtGui.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(20, 60, 1631, 16))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.upButton = QtGui.QPushButton(self.centralwidget)
        self.upButton.setGeometry(QtCore.QRect(450, 587, 41, 40))
        self.upButton.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("UpArrow.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.upButton.setIcon(icon)
        self.upButton.setObjectName(_fromUtf8("upButton"))
        self.downButton = QtGui.QPushButton(self.centralwidget)
        self.downButton.setGeometry(QtCore.QRect(500, 587, 41, 40))
        self.downButton.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("DownArrow.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.downButton.setIcon(icon1)
        self.downButton.setObjectName(_fromUtf8("downButton"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1679, 36))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabRules.setCurrentIndex(0)
        self.tabSource.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "FLExTrans Live Rule Tester", None))
        self.tabRules.setTabText(self.tabRules.indexOf(self.tab_transfer_rules), _translate("MainWindow", "Transfer", None))
        self.tabRules.setTabText(self.tabRules.indexOf(self.tab_interchunk_rules), _translate("MainWindow", "Interchunk", None))
        self.tabRules.setTabToolTip(self.tabRules.indexOf(self.tab_interchunk_rules), _translate("MainWindow", "Not Implemented", None))
        self.tabRules.setTabText(self.tabRules.indexOf(self.tab_postchunk_rules), _translate("MainWindow", "Postchunk", None))
        self.tabRules.setTabToolTip(self.tabRules.indexOf(self.tab_postchunk_rules), _translate("MainWindow", "Not Implemented", None))
        self.label.setText(_translate("MainWindow", "Transfer File", None))
        self.TransferFileBrowseButton.setText(_translate("MainWindow", "Browse...", None))
        self.BilingFileBrowseButton.setText(_translate("MainWindow", "Browse...", None))
        self.label_2.setText(_translate("MainWindow", "Bilingual Dict. File", None))
        self.tabSource.setTabText(self.tabSource.indexOf(self.tab_select_words), _translate("MainWindow", "Select Words", None))
        self.tabSource.setTabText(self.tabSource.indexOf(self.tab_select_sentences), _translate("MainWindow", "Select Sentences", None))
        self.tabSource.setTabText(self.tabSource.indexOf(self.tab_manual_entry), _translate("MainWindow", "Manual Entry", None))
        self.label_3.setText(_translate("MainWindow", "Target Text", None))
        self.label_4.setText(_translate("MainWindow", "Source Text", None))
        self.TestButton.setText(_translate("MainWindow", "&Test", None))
        self.CloseButton.setText(_translate("MainWindow", "Close", None))
        self.label_5.setText(_translate("MainWindow", "Select Rules to Test", None))
        self.label_6.setText(_translate("MainWindow", "Information", None))
        self.SourceTextName.setText(_translate("MainWindow", "Source Text Name", None))
        self.ChooseSourceButton.setText(_translate("MainWindow", "Choose...", None))
        self.refreshButton.setText(_translate("MainWindow", "&Refresh", None))
        self.selectAllButton.setText(_translate("MainWindow", "&Select All", None))

