# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TestbedLog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 546)
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.logTreeView = QtWidgets.QTreeView(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.logTreeView.setFont(font)
        self.logTreeView.setObjectName("logTreeView")
        self.verticalLayout.addWidget(self.logTreeView)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.OKButton = QtWidgets.QPushButton(self.centralwidget)
        self.OKButton.setObjectName("OKButton")
        self.horizontalLayout_2.addWidget(self.OKButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.editTestbedButton = QtWidgets.QPushButton(self.centralwidget)
        self.editTestbedButton.setEnabled(False)
        self.editTestbedButton.setObjectName("editTestbedButton")
        self.horizontalLayout_2.addWidget(self.editTestbedButton)
        spacerItem2 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.ZoomLabel = QtWidgets.QLabel(self.centralwidget)
        self.ZoomLabel.setObjectName("ZoomLabel")
        self.horizontalLayout_2.addWidget(self.ZoomLabel)
        self.fontSizeSpinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.fontSizeSpinBox.setObjectName("fontSizeSpinBox")
        self.horizontalLayout_2.addWidget(self.fontSizeSpinBox)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Testbed Log"))
        self.OKButton.setText(_translate("MainWindow", "OK"))
        self.editTestbedButton.setText(_translate("MainWindow", "Edit Testbed"))
        self.ZoomLabel.setText(_translate("MainWindow", "Font Size:"))
