# Form implementation generated from reading ui file 'Disambiguator.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DisambiguatorWindow(object):
    def setupUi(self, DisambiguatorWindow):
        DisambiguatorWindow.setObjectName("DisambiguatorWindow")
        DisambiguatorWindow.resize(900, 560)
        self.centralwidget = QtWidgets.QWidget(parent=DisambiguatorWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.instructionsLabel = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.instructionsLabel.setFont(font)
        self.instructionsLabel.setWordWrap(True)
        self.instructionsLabel.setObjectName("instructionsLabel")
        self.verticalLayout.addWidget(self.instructionsLabel)
        self.scrollArea = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 878, 460))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.textVerticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.textVerticalLayout.setSpacing(2)
        self.textVerticalLayout.setObjectName("textVerticalLayout")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        self.saveButton = QtWidgets.QPushButton(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.saveButton.setFont(font)
        self.saveButton.setObjectName("saveButton")
        self.buttonLayout.addWidget(self.saveButton)
        self.saveCloseButton = QtWidgets.QPushButton(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.saveCloseButton.setFont(font)
        self.saveCloseButton.setObjectName("saveCloseButton")
        self.buttonLayout.addWidget(self.saveCloseButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.buttonLayout.addItem(spacerItem)
        self.cancelButton = QtWidgets.QPushButton(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.cancelButton.setFont(font)
        self.cancelButton.setObjectName("cancelButton")
        self.buttonLayout.addWidget(self.cancelButton)
        self.verticalLayout.addLayout(self.buttonLayout)
        DisambiguatorWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(DisambiguatorWindow)
        QtCore.QMetaObject.connectSlotsByName(DisambiguatorWindow)

    def retranslateUi(self, DisambiguatorWindow):
        _translate = QtCore.QCoreApplication.translate
        DisambiguatorWindow.setWindowTitle(_translate("DisambiguatorWindow", "Disambiguation Editor"))
        self.instructionsLabel.setText(_translate("DisambiguatorWindow", "Ambiguous words are highlighted. Use the drop-down boxes to choose the correct alternative for each one, then click Save or Save and Close."))
        self.saveButton.setToolTip(_translate("DisambiguatorWindow", "Save the current choices to the synthesized text file."))
        self.saveButton.setText(_translate("DisambiguatorWindow", "Save"))
        self.saveCloseButton.setToolTip(_translate("DisambiguatorWindow", "Save the current choices to the synthesized text file and close this window."))
        self.saveCloseButton.setText(_translate("DisambiguatorWindow", "Save and Close"))
        self.cancelButton.setToolTip(_translate("DisambiguatorWindow", "Restore the synthesized text file to what it was when this window opened, then close."))
        self.cancelButton.setText(_translate("DisambiguatorWindow", "Cancel"))
