# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FixClusterProjectsUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(439, 148)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.OKButton = QtWidgets.QPushButton(self.centralwidget)
        self.OKButton.setGeometry(QtCore.QRect(130, 113, 81, 23))
        self.OKButton.setObjectName("OKButton")
        self.CancelButton = QtWidgets.QPushButton(self.centralwidget)
        self.CancelButton.setGeometry(QtCore.QRect(220, 113, 81, 23))
        self.CancelButton.setObjectName("CancelButton")
        self.clusterProjectsComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.clusterProjectsComboBox.setGeometry(QtCore.QRect(190, 80, 221, 22))
        self.clusterProjectsComboBox.setObjectName("clusterProjectsComboBox")
        self.clusterProjectsLabel = QtWidgets.QLabel(self.centralwidget)
        self.clusterProjectsLabel.setGeometry(QtCore.QRect(0, 80, 181, 21))
        self.clusterProjectsLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.clusterProjectsLabel.setObjectName("clusterProjectsLabel")
        self.clusterProjectsLabel_2 = QtWidgets.QLabel(self.centralwidget)
        self.clusterProjectsLabel_2.setGeometry(QtCore.QRect(50, 20, 331, 41))
        self.clusterProjectsLabel_2.setWordWrap(True)
        self.clusterProjectsLabel_2.setObjectName("clusterProjectsLabel_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Fix Cluster Projects"))
        self.OKButton.setText(_translate("MainWindow", "OK"))
        self.CancelButton.setText(_translate("MainWindow", "Cancel"))
        self.clusterProjectsLabel.setText(_translate("MainWindow", "Cluster Projects to Apply to"))
        self.clusterProjectsLabel_2.setText(_translate("MainWindow", "This tool will run the Find and Fix utility on the projects you choose in the list below."))
