# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NewEntry.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog.resize(438, 199)
        Dialog.setWhatsThis("")
        Dialog.setInputMethodHints(QtCore.Qt.ImhNone)
        Dialog.setModal(True)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 191, 21))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(10, 40, 191, 21))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(10, 70, 191, 21))
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.glossEdit = QtWidgets.QLineEdit(Dialog)
        self.glossEdit.setGeometry(QtCore.QRect(210, 100, 130, 20))
        self.glossEdit.setObjectName("glossEdit")
        self.lexemeFormEdit = QtWidgets.QLineEdit(Dialog)
        self.lexemeFormEdit.setGeometry(QtCore.QRect(210, 10, 130, 20))
        self.lexemeFormEdit.setObjectName("lexemeFormEdit")
        self.OKButton = QtWidgets.QPushButton(Dialog)
        self.OKButton.setGeometry(QtCore.QRect(130, 163, 81, 23))
        self.OKButton.setObjectName("OKButton")
        self.morphemeTypeCombo = QtWidgets.QComboBox(Dialog)
        self.morphemeTypeCombo.setGeometry(QtCore.QRect(210, 40, 130, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.morphemeTypeCombo.setFont(font)
        self.morphemeTypeCombo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.morphemeTypeCombo.setObjectName("morphemeTypeCombo")
        self.CancelButton = QtWidgets.QPushButton(Dialog)
        self.CancelButton.setGeometry(QtCore.QRect(220, 163, 81, 23))
        self.CancelButton.setObjectName("CancelButton")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(10, 100, 191, 21))
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gramCatCombo = QtWidgets.QComboBox(Dialog)
        self.gramCatCombo.setGeometry(QtCore.QRect(210, 70, 130, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.gramCatCombo.setFont(font)
        self.gramCatCombo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.gramCatCombo.setObjectName("gramCatCombo")
        self.clusterProjectsLabel = QtWidgets.QLabel(Dialog)
        self.clusterProjectsLabel.setGeometry(QtCore.QRect(10, 130, 191, 21))
        self.clusterProjectsLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.clusterProjectsLabel.setObjectName("clusterProjectsLabel")
        self.clusterProjectsComboBox = QtWidgets.QComboBox(Dialog)
        self.clusterProjectsComboBox.setGeometry(QtCore.QRect(210, 130, 221, 22))
        self.clusterProjectsComboBox.setObjectName("clusterProjectsComboBox")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.lexemeFormEdit, self.morphemeTypeCombo)
        Dialog.setTabOrder(self.morphemeTypeCombo, self.gramCatCombo)
        Dialog.setTabOrder(self.gramCatCombo, self.glossEdit)
        Dialog.setTabOrder(self.glossEdit, self.OKButton)
        Dialog.setTabOrder(self.OKButton, self.CancelButton)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Add New Target Entry"))
        self.label.setText(_translate("Dialog", "Lexeme Form"))
        self.label_4.setText(_translate("Dialog", "Morpheme Type"))
        self.label_5.setText(_translate("Dialog", "Grammatical Category"))
        self.glossEdit.setToolTip(_translate("Dialog", "Add an entry to the target lexicon."))
        self.lexemeFormEdit.setToolTip(_translate("Dialog", "Add an entry to the target lexicon."))
        self.OKButton.setText(_translate("Dialog", "OK"))
        self.morphemeTypeCombo.setToolTip(_translate("Dialog", "Add an entry to the target lexicon."))
        self.CancelButton.setText(_translate("Dialog", "Cancel"))
        self.label_6.setText(_translate("Dialog", "Gloss"))
        self.gramCatCombo.setToolTip(_translate("Dialog", "Add an entry to the target lexicon."))
        self.clusterProjectsLabel.setText(_translate("Dialog", "Cluster Projects to Apply to"))
