# Form implementation generated from reading ui file 'PasteDataWindow.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PasteDataDialog(object):
    def setupUi(self, PasteDataDialog):
        PasteDataDialog.setObjectName("PasteDataDialog")
        PasteDataDialog.resize(500, 300)
        PasteDataDialog.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(PasteDataDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.instructionLabel = QtWidgets.QLabel(parent=PasteDataDialog)
        self.instructionLabel.setWordWrap(True)
        self.instructionLabel.setObjectName("instructionLabel")
        self.verticalLayout.addWidget(self.instructionLabel)
        self.table = QtWidgets.QTableWidget(parent=PasteDataDialog)
        self.table.setObjectName("table")
        self.table.setColumnCount(0)
        self.table.setRowCount(0)
        self.verticalLayout.addWidget(self.table)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pasteButton = QtWidgets.QPushButton(parent=PasteDataDialog)
        self.pasteButton.setObjectName("pasteButton")
        self.horizontalLayout.addWidget(self.pasteButton)
        self.clearButton = QtWidgets.QPushButton(parent=PasteDataDialog)
        self.clearButton.setObjectName("clearButton")
        self.horizontalLayout.addWidget(self.clearButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=PasteDataDialog)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(PasteDataDialog)
        self.buttonBox.accepted.connect(PasteDataDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(PasteDataDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(PasteDataDialog)

    def retranslateUi(self, PasteDataDialog):
        _translate = QtCore.QCoreApplication.translate
        PasteDataDialog.setWindowTitle(_translate("PasteDataDialog", "Paste Data"))
        self.instructionLabel.setText(_translate("PasteDataDialog", "Paste interlinear data (e.g. copied from FLEx)."))
        self.pasteButton.setText(_translate("PasteDataDialog", "Paste from Clipboard"))
        self.clearButton.setText(_translate("PasteDataDialog", "Clear"))
