# Form implementation generated from reading ui file 'TestbedLog.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TestbedLogWindow(object):
    def setupUi(self, TestbedLogWindow):
        TestbedLogWindow.setObjectName("TestbedLogWindow")
        TestbedLogWindow.resize(900, 546)
        TestbedLogWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(parent=TestbedLogWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.logTreeView = QtWidgets.QTreeView(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.logTreeView.setFont(font)
        self.logTreeView.setObjectName("logTreeView")
        self.verticalLayout.addWidget(self.logTreeView)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.OKButton = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OKButton.sizePolicy().hasHeightForWidth())
        self.OKButton.setSizePolicy(sizePolicy)
        self.OKButton.setObjectName("OKButton")
        self.horizontalLayout_2.addWidget(self.OKButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.editTestbedButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.editTestbedButton.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editTestbedButton.sizePolicy().hasHeightForWidth())
        self.editTestbedButton.setSizePolicy(sizePolicy)
        self.editTestbedButton.setObjectName("editTestbedButton")
        self.horizontalLayout_2.addWidget(self.editTestbedButton)
        spacerItem2 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.ZoomLabel = QtWidgets.QLabel(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ZoomLabel.sizePolicy().hasHeightForWidth())
        self.ZoomLabel.setSizePolicy(sizePolicy)
        self.ZoomLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.ZoomLabel.setObjectName("ZoomLabel")
        self.horizontalLayout_2.addWidget(self.ZoomLabel)
        self.fontSizeSpinBox = QtWidgets.QSpinBox(parent=self.centralwidget)
        self.fontSizeSpinBox.setObjectName("fontSizeSpinBox")
        self.horizontalLayout_2.addWidget(self.fontSizeSpinBox)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        TestbedLogWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(TestbedLogWindow)
        QtCore.QMetaObject.connectSlotsByName(TestbedLogWindow)

    def retranslateUi(self, TestbedLogWindow):
        _translate = QtCore.QCoreApplication.translate
        TestbedLogWindow.setWindowTitle(_translate("TestbedLogWindow", "Testbed Log"))
        self.OKButton.setText(_translate("TestbedLogWindow", "OK"))
        self.editTestbedButton.setText(_translate("TestbedLogWindow", "Edit Testbed"))
        self.ZoomLabel.setText(_translate("TestbedLogWindow", "Font Size:"))
