rem GENERATED FILE - DO NOT EDIT.
rem Generated by Dev/updateLanguageFiles.py from the authoritative UI-language list in Dev/Lib/UILanguages.py.
rem To change the language list, edit that module and rerun:  python Dev/updateLanguageFiles.py
rem Callers do:  call "%~dp0<relative path>\lang_codes.bat"  and then loop with:  for %%L in (%LANG_CODES%) do ...
set LANG_CODES=es fr de
