#
#   updateLanguageFiles.py
#
#   Build tool. Regenerates every file that needs the FLExTrans UI-language list but cannot import Dev/Lib/UILanguages.py (the authoritative list) directly:
#
#     Dev/lang_codes.bat                                                - sets LANG_CODES for the batch scripts (CreateInstaller.bat, the translation-processing .bat files).
#     Installer/InstallerResources/LangForInstallerScript/languages.nsh - the NSIS registrations, per-language includes, and macros inserted by FLExTrans-installer.nsi.
#     crowdin.yml                                                       - the Crowdin sync config (source .ts patterns with per-language ignore lists).
#
#   The generated files are committed to the repo (CI and manual builds read them without running Python), and CreateInstaller.bat runs this script so they can never drift
#   from UILanguages.py.
#
#   Run it after changing LANGUAGES in Dev/Lib/UILanguages.py:
#     python Dev/updateLanguageFiles.py
#
#   See Dev/README-AddingUILanguage.md for the complete checklist for adding a new UI language.

import os
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(REPO, 'Dev', 'Lib'))

import UILanguages

# The folders whose .ts files Crowdin translates, in the order they appear in crowdin.yml.
CROWDIN_TRANSLATION_DIRS = ['/Dev/Lib/translations', '/Dev/Lib/Windows/translations', '/Dev/Modules/translations', '/Dev/TopLevel/translations']


def generatedHeader(commentPrefix):
    '''The do-not-edit banner placed at the top of every generated file, with the given per-format comment prefix ('rem', ';', or '#').'''

    lines = ['GENERATED FILE - DO NOT EDIT.',
             'Generated by Dev/updateLanguageFiles.py from the authoritative UI-language list in Dev/Lib/UILanguages.py.',
             'To change the language list, edit that module and rerun:  python Dev/updateLanguageFiles.py']

    return '\n'.join(f'{commentPrefix} {line}' for line in lines) + '\n'


def buildLangCodesBat():
    '''The batch fragment that scripts `call` to get the translation language codes (every UI language except English) in LANG_CODES.
    It must not use setlocal: a setlocal inside a called script would be undone when the call returns, wiping LANG_CODES.'''

    text = generatedHeader('rem')
    text += 'rem Callers do:  call "%~dp0<relative path>\\lang_codes.bat"  and then loop with:  for %%L in (%LANG_CODES%) do ...\n'
    text += 'set LANG_CODES={codes}\n'.format(codes=' '.join(UILanguages.translationCodes()))

    return text


def buildLanguagesNsh():
    '''The NSIS include holding everything per-language in the installer script: the MUI language registrations, the per-language string includes, and the macros that
    FLExTrans-installer.nsi inserts for the language picker, the $LANGUAGE -> string-set mapping, and the bundled XXE addon zips.'''

    # ${LANG_German} etc. are defined by the MUI_LANGUAGE registrations; NSIS names the constant after the language file, uppercased.
    langConst = lambda lang: 'LANG_' + lang.nsisName.upper()
    prefix = lambda lang: lang.code.upper()

    text = generatedHeader(';')
    text += ';\n'
    text += '; Included by FLExTrans-installer.nsi after the MUI page macros. The include order below matters: the MUI_LANGUAGE registrations define the ${LANG_*} constants that\n'
    text += '; the per-language .nsh files reference in their LangStrings.\n'
    text += '\n'
    text += '; MUI language registrations, one per UI language.\n'

    for lang in UILanguages.LANGUAGES:
        text += '!insertmacro MUI_LANGUAGE "{name}"\n'.format(name=lang.nsisName)

    text += '\n'
    text += '; Per-language string definitions (LangStrings and XX_* compile-time constants). Paths are relative to the makensis working directory (the Installer folder).\n'

    for lang in UILanguages.LANGUAGES:
        text += '!include "InstallerResources\\LangForInstallerScript\\{code}.nsh"\n'.format(code=lang.code)

    text += '\n'
    text += '; Push pairs for the LangDLL language picker (inserted inside ShowLanguageDialog). The order of the pairs — the order of LANGUAGES in UILanguages.py — is the picker order.\n'
    text += '!macro FLEXTRANS_LANG_PICKER_PUSHES\n'

    for lang in UILanguages.LANGUAGES:

        text += '  Push ${{{const}}}\n'.format(const=langConst(lang))
        text += '  Push ${{{prefix}_DISPLAY_NAME}}\n'.format(prefix=prefix(lang))

    text += '!macroend\n'
    text += '\n'
    text += '; Map the chosen $LANGUAGE to its language code and translated string set (inserted inside SetLanguageCode, after ASSIGN_LANG_STRINGS is defined).\n'
    text += '!macro FLEXTRANS_SET_LANGCODE_CHAIN\n'

    for i, lang in enumerate(UILanguages.LANGUAGES):

        keyword = '${If}' if i == 0 else '${ElseIf}'
        text += '  {keyword} $LANGUAGE == ${{{const}}}\n'.format(keyword=keyword, const=langConst(lang))
        text += '    !insertmacro ASSIGN_LANG_STRINGS "{prefix}"\n'.format(prefix=prefix(lang))

    text += '  ${Else}\n'
    text += '    ; Fallback to English\n'
    text += '    !insertmacro ASSIGN_LANG_STRINGS "{prefix}"\n'.format(prefix=UILanguages.SOURCE_CODE.upper())
    text += '  ${EndIf}\n'
    text += '!macroend\n'
    text += '\n'
    text += '; File lines bundling each translation language\'s XXE addon zip (inserted in the XXE section; ${GIT_FOLDER} and ${PRODUCT_VERSION} are defined by the .nsi).\n'
    text += '!macro FLEXTRANS_ADDON_ZIP_FILES\n'

    for code in UILanguages.translationCodes():
        text += '  File "${{GIT_FOLDER}}\\Installer\\AddOnsForXMLmind_{code}${{PRODUCT_VERSION}}.zip"\n'.format(code=code)

    text += '!macroend\n'

    return text


def buildCrowdinYml():
    '''The Crowdin sync config: for each translation folder, the base .ts files are the translation sources and every per-language _XX.ts is ignored (those are Crowdin's output,
    not its input). Languages whose Crowdin id differs from our two-letter code get a language_mapping entry.'''

    text = generatedHeader('#')

    mapped = [lang for lang in UILanguages.LANGUAGES if lang.crowdinId]

    if mapped:

        text += 'language_mapping:\n'

        for lang in mapped:

            text += '  - crowdin_language_id: {crowdinId}\n'.format(crowdinId=lang.crowdinId)
            text += '    custom_code: {code}\n'.format(code=lang.code)

    text += 'files:\n'

    for transDir in CROWDIN_TRANSLATION_DIRS:

        text += '  - source: {transDir}/*.ts\n'.format(transDir=transDir)
        text += '    translation: {transDir}/%file_name%_%two_letters_code%.ts\n'.format(transDir=transDir)
        text += '    type: qt\n'
        text += '    ignore:\n'

        for code in UILanguages.translationCodes():
            text += '      - {transDir}/*_{code}.ts\n'.format(transDir=transDir, code=code)

    return text


def writeIfChanged(path, text):
    '''Write `text` to `path` (CRLF line endings, UTF-8) only when the content differs, and report which. Skipping unchanged files keeps timestamps and version control quiet.'''

    fileText = text.replace('\n', '\r\n')

    if os.path.exists(path):

        with open(path, 'rb') as f:

            if f.read() == fileText.encode('utf-8'):

                print(f'  unchanged: {os.path.relpath(path, REPO)}')
                return

    with open(path, 'wb') as f:
        f.write(fileText.encode('utf-8'))

    print(f'  wrote:     {os.path.relpath(path, REPO)}')


def main():

    print('Regenerating language-derived files from Dev/Lib/UILanguages.py ({codes}):'.format(codes=', '.join(UILanguages.allCodes())))

    writeIfChanged(os.path.join(REPO, 'Dev', 'lang_codes.bat'), buildLangCodesBat())
    writeIfChanged(os.path.join(REPO, 'Installer', 'InstallerResources', 'LangForInstallerScript', 'languages.nsh'), buildLanguagesNsh())
    writeIfChanged(os.path.join(REPO, 'crowdin.yml'), buildCrowdinYml())


if __name__ == '__main__':
    main()
